apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-cert
  namespace: ingress-nginx
spec:
  secretName: wordpress-tls  # The secret where the cert will be stored
  issuerRef:
    name: letsencrypt-prod  # Refers to your ClusterIssuer
    kind: ClusterIssuer
  commonName: kubernetics.co.uk
  dnsNames:
    - kubernetics.co.uk
    - www.kubernetics.co.uk
